services: mongodb

notifications:
  email: false

language: ruby
rvm:
  - 1.9.3
  - 2.3.3
  - jruby-19mode

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
  - MONGOID_VERSION=6

gemfile:
  - Gemfile