services: mongodb

notifications:
  email: false

language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode

gemfile:
  - Gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-3.x.gemfile
  - gemfiles/mongoid-2.x.gemfile

